pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:prasadmahabare/homework_acs560.git
          - cd homework_acs560.git
          - git push --mirror git@github.com:MahabarePS/software_engineering.git