# Generated by Django 4.2.6 on 2023-10-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='categorey',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='updatedAt',
        ),
    ]
